stages:
  download:
    cmd: python src/download.py
    deps:
    - src/download.py
    params:
    - download.n_loc
    - download.year
    outs:
    - data/weather.csv
  prepare:
    cmd: python src/prepare.py data/weather.csv data/groundTruth.csv
    deps:
    - data/weather.csv
    - src/prepare.py
    params:
    - prepare.seed
    outs:
    - data/groundTruth.csv
  process:
    cmd: python src/process.py data/weather.csv data/predictedTruth.csv
    deps:
    - data/weather.csv
    - src/process.py
    outs:
    - data/predictedTruth.csv
  evaluate:
    cmd: python src/evaluate.py data/groundTruth.csv data/predictedTruth.csv
    deps:
    - data/groundTruth.csv
    - data/predictedTruth.csv
    - src/evaluate.py
    outs:
    - data/R2_score.txt
    metrics:
    - data/metrics.json
