stages:
  download:
    cmd: python src/download.py
    deps:
    - src/download.py
    params:
    - download.n_loc
    - download.year
    outs:
    - data/weather.csv
  prepare:
    cmd: python src/prepare.py data/weather.csv data/groundTruth.csv
    deps:
    - data/weather.csv
    - src/prepare.py
    params:
    - prepare.seed
    outs:
    - data/groundTruth.csv
